name: Build & Deploy to Github Pages

on:
  push:
    branches: [master, main]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  node-to-gh:
    runs-on: ubuntu-latest
    name: Build & Deploy to Github Pages
    steps:
      - id: node-to-gh
        uses: fdelmazo/node-to-gh-action@v1